version: 3

tasks:
  copy-basic-files:
    desc: Create basic config files based on .dist
    cmds:
      - test -f .env || cp .env.dist .env

  init:
    desc: Initialize basic config to run application with Kubernetes
    cmds:
      - task: copy-basic-files

  start:
    desc: Prepare and run application in kubernetes
    cmds:
      - task: build:image

  build:image:
    desc: Build basic application image
    cmds:
      - docker-compose build
